#!/bin/bash

# TODO
# Deploy the new data / commit

Purpose of this script:

- Generate a git pull on all the concerned machines
- Restart the redis server - repopulate the DB with new columns if need be.
- Restart the daemons
