#! /usr/bin/env python3
import argparse
import os
from scxkw.tools.vampires_processing import WrongComputerException
from scxkw.tools.vampires_processing.processing import check_for_new_folders, setup_logger

logger = setup_logger(__file__)

parser = argparse.ArgumentParser("scxkw-vamp-process-check-new-folders")

def main():
    if os.environ.get("WHICHCOMP", "") != "5":
        msg = "This script must be run on scexao5"
        logger.error(msg)
        raise WrongComputerException(msg)
    logger.info("Script ran")
    parser.parse_args()
    check_for_new_folders()

if __name__ == "__main__":
    main()