#!/usr/bin/env python3

import argparse
from pathlib import Path

from scxkw.tools.frameids import (
    get_fits_info,
    assign_new_frameids,
    rename_and_update_header,
)


def main():
    parser = argparse.ArgumentParser(
        description="Reassign string-based FRAMEIDs in FITS files"
    )
    parser.add_argument(
        "filelist", type=Path, help="Input text file with .fits/.fits.fz filenames on each line"
    )
    parser.add_argument(
        "-f", "--fix", action="store_true", help="If FRAMEID order is not chronological, fix the files"
    )
    args = parser.parse_args()

    input_files = list(map(Path, args.filelist.read_text().split("\n")))

    # Step 1: Read FITS headers
    df = get_fits_info(input_files)
    if df.empty:
        print("No valid FITS files found. Exiting.")
        return

    # Step 2: Assign new FRAMEIDs
    df_new = assign_new_frameids(df)
    filename = Path().cwd() / "frameid_table.csv"
    df_new.to_csv(filename, index=False)
    print(f"Saved table to {filename}")

    # check if new frameids match old frameids
    if (df_new["new_frameid"] == df_new["frameid"]).all():
        print("All FRAMEIDs are in sequential and chronological order")
        return

    num_to_reassign = (df_new["new_frameid"] != df_new["frameid"]).sum()
    print(f"There are {num_to_reassign} bad FRAMEIDs!")
    if args.fix:
        # Step 3: Rename files and update headers
        print("Reassigning FRAMEIDs")
        rename_and_update_header(df_new)
        print("FRAMEIDs reassigned and files renamed successfully.")
    else:
        print("Re-run with `--fix` to fix the bad FRAMEIDs")


if __name__ == "__main__":
    main()
