#!/bin/bash
set -e # script exits if a command fails
set -u # script exits if unset variable is used

echo -e "================================"
echo -e "VAMPIRES DATA ARCHIVING RECOVERY"
echo -e "================================"


# Check if a folder was provided
if [ -z "$1" ]; then
    echo -e "Usage: $0 <folder>"
    exit 1
fi

folder=$(realpath "$1")

# Check if the folder exists
if [ ! -d "$folder" ]; then
    echo -e "Error: Folder '$folder' does not exist."
    exit 1
fi

echo -e "\n--------------------------------------------------"
echo -e "Cleaning up folder\n"

echo -e "!!! WARNING !!!"
echo -e "We are about to delete the following folders:"
echo -e "- $folder/vcam1"
echo -e "- $folder/vcam2"
echo -e "- $folder/vsolo*" 
echo -e "- $folder/vsync" 
echo -e "- $folder/vbad"
echo -e "- $folder/**/tmp"
echo -e "- $folder/vgen2"
echo -e "Waiting 10 seconds before continuing, CTRL+C now to cancel..."
sleep 10

set +e
rm -rf "$folder/vcam1" "$folder/vcam2" "$folder/vsolo*"* "$folder/vsync" "$folder/vbad" "$folder/**/tmp" "$folder/vgen2"
set -e

echo -e "\n--------------------------------------------------"
echo -e "Restoring backups\n"

if [ -d "$folder/vcam1_hlinkbak" ]; then
    echo "$folder/vcam1_hlinkbak -> $folder/vcam1"
    mv "$folder/vcam1_hlinkbak" "$folder/vcam1"
fi
if [ -d "$folder/vcam2_hlinkbak" ]; then
    echo "$folder/vcam2_hlinkbak -> $folder/vcam2"
    mv "$folder/vcam2_hlinkbak" "$folder/vcam2"
fi

echo -e "\n--------------------------------------------------"
echo -e "Folder restored\n"
