#! /usr/bin/env python3
import argparse
import os
from scxkw.tools.vampires_archiving import WrongComputerException, check_for_new_folders

parser = argparse.ArgumentParser("scxkw-vamp-check-archive-folder")

def main():
    if os.environ.get("WHICHCOMP", "") != "5":
        msg = "This script must be run on scexao5"
        raise WrongComputerException(msg)
    parser.parse_args()
    check_for_new_folders()



if __name__ == "__main__":
    main()