#!/usr/bin/env python3

import argparse
from pathlib import Path

from scxkw.tools.frameids import (
    get_fits_info,
    assign_new_frameids,
    rename_and_update_header,
)


def main():
    parser = argparse.ArgumentParser(
        description="Reassign string-based FRAMEIDs in FITS files"
    )
    parser.add_argument(
        "files", type=Path, nargs="+", help="Input .fits/.fits.fz filenames"
    )
    args = parser.parse_args()

    # Step 1: Read FITS headers
    df = get_fits_info(args.files)
    if df.empty:
        print("No valid FITS files found. Exiting.")
        return

    # Step 2: Assign new FRAMEIDs
    df_new = assign_new_frameids(df)
    df_new.to_csv(Path().cwd() / "frameid_table.csv", index=False)
    # Step 3: Rename files and update headers
    rename_and_update_header(df_new)

    print("FRAMEIDs reassigned and files renamed successfully.")


if __name__ == "__main__":
    main()
