#!/bin/bash
set -e # script exits if a command fails
set -u # script exits if unset variable is used
set -o pipefail # fail fast on pipes and print error

# Check for help flags
for arg in "$@"; do
    if [ "$arg" == "--help" ] || [ "$arg" == "-h" ]; then
        echo -e "Usage: $0 <folder>"
        # Add help message or behavior here
        exit 0
    fi
done

# Check if a folder was provided
if [ -z "$1" ]; then
    echo -e "Usage: $0 <folder>"
    exit 1
fi


folder=$(realpath "$1")

# Check if the folder exists
if [ ! -d "$folder" ]; then
    echo -e "Error: Folder '$folder' does not exist."
    exit 1
fi

# Function to check disk space
check_disk_space() {
    local mount_point
    mount_point=$(df --output=target "$1" | tail -1)
    local required_space_gb="$2"

    # Ensure both arguments are provided
    if [[ -z "$mount_point" || -z "$required_space_gb" ]]; then
        echo -e "Usage: check_disk_space <mount_point> <required_space_gb>"
        echo -e "Recommended to use inside a tmux!"
        return 1
    fi

    # Get available space in GB
    local available_space_gb
    available_space_gb=$(df -BG "$mount_point" --output=avail | tail -1 | tr -d 'G')

    # Compare available space with required space
    if (( available_space_gb >= required_space_gb )); then
        echo -e "Sufficient space: ${available_space_gb}GB available on $mount_point."
        return 0
    else
        echo -e "Insufficient space: ${available_space_gb}GB available, but ${required_space_gb}GB required."
        return 1
    fi
}

echo -e "======================="
echo -e "VAMPIRES DATA ARCHIVING"
echo -e "======================="


folder_size_gb=$(du -sB1G "$folder" 2>/dev/null | awk '{print $1}' | tr -d 'G')
needed_size_gb=$((folder_size_gb * 2))

check_disk_space "$folder" "$needed_size_gb"

echo -e "\n--------------------------------------------------"
echo -e "Running sync+deint\n"

scxkw-vamp-syncdeint "$folder"
scxkw-vamp-summary "$folder"

echo -e "\n--------------------------------------------------"
echo -e "Running consolidate\n"

scxkw-fitsframe-consolidate "$folder"

echo -e "\n--------------------------------------------------"
echo -e "Cleaning up folder\n"

set +e # rm -rf will fail if vbad or **/tmp folders don't exist, which is OK
rm -rf "$folder/vcam1" "$folder/vcam2" "$folder/vsolo1" "$folder/vsolo2" "$folder/vsync" "$folder/vbad" "$folder/**/tmp"
set -e # back to safety!

echo -e "\n--------------------------------------------------"
echo -e "Fixing headers\n"

scxkw-fix-headers "$folder"/vgen2

echo -e "\n--------------------------------------------------"
echo -e "Assigning frame IDS\n"

scxkw-assign-frameids -f "$folder" -v

echo -e "\n--------------------------------------------------"
echo -e "Compressing with fpack\n"

# the find command gets all the filenames and puts them in a list
#
# fpack is using rice compression (-r) with printing (-v) overwriting the original (-D)
# and suppressing any prompts -Y
find "$folder/vgen2" -name "VMP*.fits" -type f -print0 | xargs -0 -P 50 -n1 -- fpack -r -v -D -Y

echo -e "\n--------------------------------------------------"
echo -e "Preparing manifest\n"

folder_date=$(basename "$folder")
scxkw-g2archive-manifest -o "${folder}/manifest_VMP_${folder_date}.csv" -p VMP "$folder"/vgen2/VMP*.fits.fz

echo -e "\n--------------------------------------------------"
echo -e "Syncing to scexao6\n"

rsync -arxuh --progress -e "ssh -T -c aes128-ctr -o Compression=no -o ConnectTimeout=10 -x" --exclude=lost+found --exclude=vcam* "$folder" sc6l:/mnt/tier1/2_ARCHIVED_DATA/

echo -e "======================="
echo -e "        FINISHED"
echo -e "======================="

