#! /usr/bin/env python3
import os
from scxkw.tools.vampires_archiving import WrongComputerException, load_table
import libtmux

def get_or_create_tmux_window(session_name: str):
    server = libtmux.Server()

    # Find or create the session
    session = server.find_where({"session_name": session_name})
    if session is None:
        session = server.new_session(session_name=session_name, attach=False, kill_session=True)
    
    # If no window name is given, return the attached (first) window
    return session.attached_window
    
def main():
    if os.environ.get("WHICHCOMP", "") != "5":
        msg = "This script must be run on scexao5"
        raise WrongComputerException(msg)
    table = load_table()
    sub_table = table.query("not processed")

    for _, row in sub_table.iterrows():
        path = row["scexao5_path"]
        session_name = f"vamp-archive-{row['utc_date']}"
        print(f"Launching archive process for folder: {path} in tmux: {session_name}")
        window = get_or_create_tmux_window(session_name)
        pane = window.attached_pane
        pane.send_keys(f"scxkw-vamp-archive {path}")

if __name__ == "__main__":
    main()