#!/bin/bash

# Move pwd such that ${PWD}/cams/SCExAO.py
cd ${HOME}/src/scxkw/conf

# SIMULATOR
#g2cam --cam=SCEXAO --loglevel=20 --log=g2cam.log --stderr --gen2host=g2sim1.subaru.nao.ac.jp --obcpnum=16
# ACTUAL
g2cam --cam=SCEXAO --loglevel=20 --log=g2cam.log --stderr --gen2host=g2ins1.sum.subaru.nao.ac.jp --obcpnum=16
