#!/usr/bin/env python
__doc__ = """
Create CSV file from FITS files

Usage:
    scxkw-header-table (-h | --help)
    scxkw-header-table [-q] [-j NPROC] [-o NAME] INPUT ...

Options:
    -h, --help              Show this help message.
    -o NAME, --output=NAME  Specify output name [default: header_table.csv].
    -j NPROC                Use process pool with NPROC processed [default: 1]
    -q, --quiet             Silence progress bar
"""
from docopt import docopt
from pathlib import Path
from typing import List
import logging
import click

from scxkw.tools.header_table import header_table

logger = logging.getLogger(__name__)

def main():
    args = docopt(__doc__)
    # get input directories
    paths = [Path(p) for p in args["INPUT"]]
    logger.debug(f"Loading {len(paths)} files")

    output = Path(args["--output"])
    if output.exists():
        if not click.confirm(f"{output} exists already, would you like to overwrite it?", default=False):
            return

    logger.debug(f"Saving output to {output.absolute()}")
    table = header_table(sorted(paths), quiet=args["--quiet"], nproc=args["-j"])
    table.to_csv(output, index=False)
    click.echo(f"Output table saved to {output}")

if __name__ == "__main__":
    main()