#! /usr/bin/env python3
import os
from scxkw.tools.vampires_processing import WrongComputerException, get_or_create_tmux_window
from scxkw.tools.vampires_processing.processing import load_table, setup_logger
import time

logger = setup_logger(__file__)

def main():
    if os.environ.get("WHICHCOMP", "") != "5":
        msg = "This script must be run on scexao5"
        raise WrongComputerException(msg)
    logger.info("Script ran")
    table = load_table().sort_values("utc_date")
    sub_table = table.query("not processed")

    for _, row in sub_table.iterrows():
        path = row["scexao5_path"]
        session_name = f"vamp-process-{row['utc_date']}"
        logger.info(f"Launching processing process for folder: {path} in tmux: {session_name}")
        window = get_or_create_tmux_window(session_name)
        pane = window.attached_pane
        pane.send_keys(f"scxkw-vamp-process-folder {path}")
        logger.info("Waiting for process to finish before launching further processes.")
        while pane.pane_current_command not in (None, "bash", "zsh", "sh"):
            time.sleep(10)

if __name__ == "__main__":
    main()