#! /usr/bin/env python3
import argparse
import os
import pathlib
from scxkw.tools.vampires_processing import WrongComputerException
from scxkw.tools.vampires_processing.archiving import load_table, crosscheck_scexao6_sdata, setup_logger

logger = setup_logger(__file__)

parser = argparse.ArgumentParser("scxkw-vamp-archive-check-sc6-data")
parser.add_argument("folder", type=pathlib.Path, nargs="*")

def main():
    if os.environ.get("WHICHCOMP", "") != "5":
        msg = "This script must be run on scexao5"
        logger.error(msg)
        raise WrongComputerException(msg)
    
    logger.info("Script ran")
    
    args = parser.parse_args()
    if len(args.folder) == 0:
        table = load_table()
        if table is None:
            return
        # by default, try data that's transferred but unverified
        folders = table.query("transferred_to_scexao6 and not safe_on_scexao6")["scexao5_path"]
    else:
        folders = args.folder
    
    if len(folders) == 0:
        logger.info("There are no unchecked folders on scexao5")
        return
    bad_folders = []
    for folder in folders:
        logger.info(f"Cross-checking folder: {folder}")
        bad_files = crosscheck_scexao6_sdata(pathlib.Path(folder))
        if bad_files:
            logger.warning("Bad files found!")
            filename = pathlib.Path(folder) / "bad_sc6_files.txt"
            with filename.open("w") as fh:
                fh.write("\n".join(bad_files))
                fh.write("\n")
            logger.info(f"Wrote a list of bad filenames to {filename.absolute()}")
            bad_folders.append(folder)

    if len(bad_folders) > 0:
        logger.info(f"The following folders have missing or bad files:")
        logger.info(", ".join(str(folder) for folder in bad_folders))

if __name__ == "__main__":
    main()